name: 'Docker Deploy Action'

description: >
  🪂  A Github Action to deploy pages conveniently

branding:
  icon: 'command'
  color: 'red'

inputs:
  id:
    description: The deploy id
    required: false
  hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}       
    required: true
  hub_password:
    description: Docker Hub authentication token
    required: true
  hub_token:
    description: Docker Hub authentication token
    required: true
  action_path:
    description: Path to the dockerfile from which to build the image
    required: true
  credentials:
    description: 'The gcloud credentials'
    required: true
  image_name:
    description: Tag to use for the new image
    required: true
  dockerfile_path:
    description: Path to the dockerfile from which to build the image
    required: true
  initiate_pauli_sum:
    description: Build args
    required: false
    default: ""
  docker_hub_repo_short_description:
    description: Short description text for the docker hub repo
    required: true
  docker_hub_repo_readme_file_path:
    description: |
      Path of the md file which will be used as the docker hub repo readme
    required: true
  cache_src:
    description: Path for the docker cache source
    required: false
    default: /tmp/.buildx-cache
  cache_dest:
    description: Path for the docker cache destination
    required: false
    default: /tmp/.buildx-cache-new
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  repository:
    description: 'The deploy repository'
    default: ${{ github.repository }}
    required: false

outputs:
  artifact:
    description: Collect artifact outputs
    value: ${{ toJSON(steps.artifact.outputs) }}
  variables:
    description: Collect variables outputs
    value: ${{ toJSON(steps.variables.outputs) }}

runs:
  using: composite
  steps:
    - name: Remove Existing Connection
      shell: bash
      env:
        JOB_ID: ${{ inputs.id }}
      run: |
        HEADER="Accept: application/vnd.github+json"
        /home/runner/work/_actions/eq19/eq19/v1/.github/entrypoint/init.sh

        #See: https://docs.github.com/en/rest/actions/self-hosted-runners
        TOTAL_COUNT=$(gh api -H "${HEADER}" /repos/${{ github.repository }}/actions/runners --jq '.total_count')
        RUNNER_ID=$(gh api -H "${HEADER}" /repos/${{ github.repository }}/actions/runners --jq '.runners.[].id')
        if (( $TOTAL_COUNT != 0 )); then gh api --method DELETE -H "${HEADER}" /repos/${{ github.repository }}/actions/runners/${RUNNER_ID}; fi 

    - name: View context attributes
      uses: actions/github-script@v7
      env:
        JOB_ID: ${{ inputs.id }}
      with:
        script: console.log(context)

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.hub_username }}
        password: ${{ inputs.hub_token }}
        
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        allow-prereleases: true

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip

    - name: Install dependencies
      shell: bash
      run: |
        ##python -m pip -q install --upgrade pip
        ##python -m pip -q install -r ${{ inputs.action_path }}/dataFile/requirements.txt
  
        #python -m pip -q install -e ./.github/entrypoint/artifact/python
        #iree-compile --iree-llvmcpu-list-targets && iree-run-module --list_drivers

        #Ref: https://github.com/iree-org/iree-experimental
        #python ${{ inputs.action_path }}/pythonCode/testIREE.py
        
        #Ref: https://github.com/tsoding/JelloVM
        ##cd ${{ inputs.action_path }} && javac javaCode/Main.java
        ##python app.py output.txt && cat dataFile/results/output.txt

        #Ref: https://github.com/eq19/maps/tree/v3/pythonCode
        #python ${{ github.workspace }}/.github/entrypoint/artifact/python/gellmann.py
        #cd ${{ inputs.action_path }}/pythonCode && python npreader.py -h && python map.py -h

        #Ref: https://github.com/ccxt/ccxt/blob/4.4.40/python/ccxt/async_support/indodax.py#L195
        mv -f ${{ inputs.action_path }}/dataFile/user_data ${{ github.workspace }}/
        cd ${{ github.workspace }}/user_data/build_helpers && ./install_ta-lib.sh > /dev/null 2>&1
        cd ${{ github.workspace }} && mv -f user_data/config.json .
        
        sed -i "s|/BTC|/IDR|g" config.json
        sed -i "s|binance|indodax|g" config.json
        sed -i "s|your_exchange_key|${ACCESS_API}|g" config.json
        sed -i "s|your_exchange_secret|${ACCESS_KEY}|g" config.json
        sed -i "s|your_telegram_chat_id|${MESSAGE_ID}|g" config.json
        sed -i "s|your_telegram_token|${MESSAGE_TOKEN}|g" config.json

    - name: 🚀 Initiate Lexer
      uses: devcontainers/ci@v0.3
      with:
        push: always
        skipContainerUserIdUpdate: true
        imageName: ${{ inputs.image_name }}
        imageTag: target-${{ github.run_number }}
        configFile: ${{ inputs.action_path }}/.devcontainer.json
        runCmd: freqtrade trade --config config.json --strategy SampleStrategy --dry-run

    - name: 💎 Variables
      id: variables
      shell: bash
      run: |
        BASE_NAME=$(basename ${{ inputs.image_name }})
        IFS=', '; array=($(curl -L -s 'https://registry.hub.docker.com/v2/repositories/${{ inputs.image_name }}/tags?page_size=1024' | jq -rc '."results"[]["name"]' | yq eval -P | sed "s/ /, /g"))
        for ((i=0; i < ${#array[@]}; i++)); do
          if [ "${array[$i]}" != "latest" ]; then
            HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ inputs.hub_username }}\", \"password\": \"${{ inputs.hub_password }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
            curl -s -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" https://hub.docker.com/v2/namespaces/${{ inputs.hub_username }}/repositories/$BASE_NAME/tags/${array[$i]}
            echo "deleted: ${{ inputs.image_name }}:${array[$i]}"
          fi
        done
