name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  id:
    description: The deploy id
    required: false
  hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}       
    required: true
  hub_password:
    description: Docker Hub authentication token
    required: true
  hub_token:
    description: Docker Hub authentication token
    required: true
  action_path:
    description: Path to the dockerfile from which to build the image
    required: true
  credentials:
    description: 'The gcloud credentials'
    required: true
  image_name:
    description: Tag to use for the new image
    required: true
  dockerfile_path:
    description: Path to the dockerfile from which to build the image
    required: true
  pauli_sum:
    description: Build args
    required: false
  docker_hub_repo_short_description:
    description: Short description text for the docker hub repo
    required: true
  docker_hub_repo_readme_file_path:
    description: |
      Path of the md file which will be used as the docker hub repo readme
    required: true
  cache_src:
    description: Path for the docker cache source
    required: false
    default: /tmp/.buildx-cache
  cache_dest:
    description: Path for the docker cache destination
    required: false
    default: /tmp/.buildx-cache-new
  failure_status:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false

outputs:
  all_outputs:
    description: Collect all outputs
    value: ${{ toJSON(steps.*.outputs) }}

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:
    - name: 💎 Reinvented
      shell: bash
      env:
        JOB_ID: ${{ inputs.id }}
        TOKEN: ${{ inputs.token }}
        BASE: "https://github.com/eq19/eq19.github.io.wiki.git"
        WIKI: "https://github.com/${{ env.TARGET_REPOSITORY }}.wiki.git"
      run: |
        if [ -d /mnt/disks/deeplearning/usr/local/sbin ]; then
          export PAULI_SUM=$(echo -n "${{ inputs.pauli_sum }}" | base64 --decode);
          export PATH=/home/runner/_work/_actions/eq19/eq19/v2/.github/entrypoint:$PATH && init.sh
        else
          exit 1
        fi

    - name: View context attributes
      uses: actions/github-script@v7
      env:
        JOB_ID: ${{ inputs.id }}
        GH_TOKEN: ${{ inputs.token }}
      with:
        script: console.log(context)

    - name: 🏗️ Collect outputs
      uses: mathiasvr/command-output@v2.0.0
      id: command
      with:
        run: |
          date +'%Y-%m-%d'
